export enum ErrorCode {
  // Auth
  INVALID_CREDENTIALS = 'AUTH_001',
  ACCOUNT_LOCKED = 'AUTH_002',
  ACCOUNT_DEACTIVATED = 'AUTH_003',
  INVALID_TOKEN = 'AUTH_004',
  TOKEN_EXPIRED = 'AUTH_005',
  EMAIL_NOT_VERIFIED = 'AUTH_006',
  INSUFFICIENT_PERMISSIONS = 'AUTH_007',

  // Validation
  VALIDATION_ERROR = 'VAL_001',
  INVALID_INPUT = 'VAL_002',

  // Resource
  RESOURCE_NOT_FOUND = 'RES_001',
  RESOURCE_CONFLICT = 'RES_002',
  RESOURCE_GONE = 'RES_003',

  // Database
  DATABASE_ERROR = 'DB_001',
  UNIQUE_CONSTRAINT = 'DB_002',
  FOREIGN_KEY_CONSTRAINT = 'DB_003',
  RECORD_NOT_FOUND = 'DB_004',

  // File
  FILE_TOO_LARGE = 'FILE_001',
  INVALID_FILE_TYPE = 'FILE_002',
  FILE_UPLOAD_FAILED = 'FILE_003',

  // Rate Limit
  RATE_LIMIT_EXCEEDED = 'RATE_001',

  // Server
  INTERNAL_ERROR = 'SRV_001',
  SERVICE_UNAVAILABLE = 'SRV_002',
}
